SSH-key-rotation-AWS/key-switcheroo

terraform-environments/instance.tf
terraform-environments/main.tf
terraform-environments/variables.tf

Terraform is able to create and update s3 buckets, ec2 instances and security groups

terraform up and running

---

ssh_key_rotator/custom_keygen.py
ssh_key_rotator/server/server.py
tests/unit/server/test_local.py
tests/unit/server/test_remote.py

- use pyhamcrest instead of normal unittest assert
- make key size a constant
- remove code duplication in keygen
- Fix bug where server logs were staying constant every run

Quick fixes from review

---

ssh_key_rotator/publisher/key_publisher.py
ssh_key_rotator/server/data_stores.py
ssh_key_rotator/server/retrieve_public_keys.py
tests/unit/server/test_local.py

- temp dir for local publisher
- fixed issues with the ssh home dir not being created when needed

Temp Dirs for local publisher & bugfixes

---

switcheroo/custom_keygen.py
switcheroo/publisher/key_publisher.py
switcheroo/server/data_stores.py
switcheroo/server/retrieve_public_keys.py
tests/end_to_end/test_publish_and_read.py
tests/unit/publisher/test_local_publisher.py
tests/unit/publisher/test_s3_publisher.py
tests/unit/server/test_local.py
tests/unit/server/test_remote.py

- Added KeyMetadata class with created_by and time_created fields
- Added methods to the publishers to publish metadata
- Started migrating some code to PathLib, still a WIP
- Added tests for S3 publisher and metadata
closes #58 
closes #51

Generate keys with metadata

---

switcheroo/server/__main__.py

- Created a __main__.py file for the retriever CLI
- Meant to replace if "__name__" == "__main__" in key retriever file that uses sys.argv

New __main__.py for retriever argparse

---

switcheroo/data_store/data_stores.py
switcheroo/data_store/s3.py
switcheroo/exceptions.py
switcheroo/server/__main__.py

KeyNotFoundException
Added raise exception to retrieve functions in data stores

KeyNotFoundException

---

switcheroo/data_store/data_stores.py
switcheroo/util.py

- opener function to restrict permissions on a file
- Instead of checking if a file exists, just use it and deal with exception
closes #52

Opener and pencil

---

README.md

Edited README file with basic program documentation. Can be edited more in the future.

Tentative program documentation

---

switcheroo/data_store/data_stores.py
switcheroo/data_store/s3.py
switcheroo/exceptions.py

Explicitly re-raise KeyNotFoundException from the file not found exception

---

tests/switcheroo_ssh/conftest.py
tests/switcheroo_ssh/end_to_end/test_publish_and_read.py

Added a test to ensure that keys are actually rotated

Some-more-ssh-tests

---

bash.sh

- absolute paths in bash script
- fix big bug in bash script that made it not work on first use

fix bug in bash script & update for full paths

---

tests/test_cloud_watch/cloudwatch/test_metrics.py

- one of the tests referenced an incorrect variable. Fixed.

Fixed typo bug in metric test

---

switcheroo/base/data_store/__init__.py
switcheroo/base/data_store/s3.py
switcheroo/base/data_store/util.py
switcheroo/base/exceptions/s3.py
switcheroo/base/serializer.py

- Added documentation for base api
- moved utility function to be private

Added documentation for base api and moved a function to be private

---

switcheroo/ssh/scripts/publish.py

- quick fix for the argparse error for the CLI. Will add more parameter validation/exception wrapping

Fixed bugs in command line scripts

---

switcheroo/ssh/__init__.py
switcheroo/ssh/data_org/publisher/__init__.py
tests/switcheroo/ssh/conftest.py
tests/switcheroo/ssh/end_to_end/test_publish_and_read.py
tests/switcheroo/ssh/integration/conftest.py
tests/switcheroo/ssh/integration/test_aws_metric_publisher.py
tests/switcheroo/ssh/integration/test_aws_metric_publishing.py
tests/switcheroo/ssh/integration/test_file_metric_publishing.py
tests/switcheroo/ssh/unit/publisher/test_local_publisher.py
tests/switcheroo/ssh/unit/publisher/test_s3_publisher.py
tests/switcheroo/ssh/unit/server/test_local.py
tests/switcheroo/ssh/unit/server/test_remote.py

Wrote integration tests for publishing SSH keys with the metrics.

Integration tests

---

poetry.lock
pyproject.toml

- added metric_system package to final distribution
- moved boto3 stubs to be available @ runtime

Fix-dist-package

---

switcheroo/ssh/__init__.py
switcheroo/ssh/data_stores/__init__.py
switcheroo/ssh/exceptions.py
switcheroo/ssh/objects/key.py

Documentation for the ssh part

---

aws_profiles/__init__.py
aws_profiles/exceptions.py
aws_profiles/profile.py
poetry.lock
pyproject.toml
tests/aws_profiles/conftest.py
tests/aws_profiles/test_profile_manager.py

-AWS Profile API
-Create AWS profiles (credential settings) and select one
-Persistent storage in JSON file
-Thoroughly tested
-Added moto (boto3 mock) to project dev dependencies

Aws-profiles

---

aws_profiles/__init__.py
pyproject.toml
switcheroo/base/__init__.py
switcheroo/base/scripts/configure.py

Added configure script that uses the aws profiles api

Added configure script

---

aws_profiles/__init__.py
tests/aws_profiles/conftest.py
tests/aws_profiles/test_profile_manager.py

- Allow deletion of only profile
- Allow invalidated credentials to be read, then removed if invalid

Allows deletion of only profile; allow invalid profiles to be loaded, then immediately forgotten

---

poetry.lock
pyproject.toml

- removed psutil, as no longer being used
-made paramiko a dev dependency only

Removed psutil, moved paramiko to be a dev dependency only

---

README.md
poetry.lock
pyproject.toml

Added instructions for how to install on the system sshd

Documentation sshd setup

---

README.md

- Moved AWS Profile management to be earlier
- clarified how to use the hostname arg

Clarify hostname, move other docs

---

switcheroo/base/__init__.py
switcheroo/base/scripts/configure.py
switcheroo/paths.py
switcheroo/ssh/scripts/__init__.py
tests/conftest.py

- We had two different ways of handling app data location for aws profiels metrics - this unifies that location into one spot

Ensure that consistent dir is used for app data amongst aws profiles and metrics
